---
abstract: 'Send UTF-8 HTML and text email with attachments and inline images, eventually using templates'
author:
  - 'Octavian Rasnita <orasnita@gmail.com>'
build_requires:
  Test::More: 0.42
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Builder-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Email::Send: 2.192
  Mail::Builder: 1.12
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
