---
abstract: 'Send UTF-8 HTML and text email with attachments and inline images, eventually using templates'
author:
  - 'Octavian Rasnita <orasnita@gmail.com>'
build_requires:
  Test::More: 0.42
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Builder-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Config::Any: 0
  Config::General: 0
  Cwd: 0
  Email::MessageID: 1.351
  Email::Send: 2.192
  Encode: 0
  HTML::Template: 0
  MIME::Tools: 5.427
  Mail::Address: 2.04
  Mail::Builder: 1.12
  Template: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
